spring:
  application:
    name: taco-cloud

  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: password
#  jms:
#    template:
#      default-destination: tacocloud.order.queue

  data:
    rest:
      base-path: /data-api

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client-id>
            client-secret: <client-secret>>
            scope:
              - profile
              - email
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

taco:
  orders:
    page-size: 10
