spring:

  application:
    name: taco-cloud

  datasource:
    generate-unique-name: false
    name: tacocloud

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

custom:
  admin-password: ${ADMIN_PASSWORD}